[package]
name = "deployer-of-worlds"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
tokio.workspace = true
clap = { version = "4.5.27", features = ["env"]}
clap_derive = "4.5.24"
deployer = { path = "../../crates/deployer" }
deployer-core = { path = "../../crates/core" }
alloy.workspace = true
axum = "0.7"
tower = "0.4"
serde.workspace = true
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.0", features = ["v4", "serde"] }
