[[actions]]
id = "deploy_x_contract"
depends_on = ["ids_of_other_action"]
type = "deploy"
data = {
  address = "0xexpected_address"
  salt = "0x.."
  bytecode = "0x.."
  abi = "0x.."
  constructor_args = ["0x...", "0xd..."]
}
output_schema = {
  type = string
}


