[package]
name = "deployer-core"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_yaml.workspace = true
serde_json = "1.0"
thiserror = "1.0"
hex = "0.4"